trigger: none

resources:
  pipelines:
    - pipeline: AROSPipeline16
      source: 'aros-development-team.AROS-pc-i386'
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Fetching triggered pipeline build ID..."
      BUILD_ID=$(echo "$(resources.pipeline.AROSPipeline16.runID)")
      echo "Build ID = $BUILD_ID"

      LOG_ID=32  # If the build pipeline changes this will need asjusted
      LOG_URL="https://dev.azure.com/aros-development-team/AROS/_apis/build/builds/$BUILD_ID/logs/$LOG_ID?api-version=6.0"
      echo "Fetching logs from: $LOG_URL"

      curl -sS \
        -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
        "$LOG_URL" \
        -o translation-stage.log

      echo "===== Custom grep output ====="
      grep -E \
        '^- warning: no catalog revision|- warning: ERROR in iconv|- warning: UTF8 conversion|- Warning: missing translation|- Warning: original string|missing in catalog description' \
        translation-stage.log || echo "No matching warnings found."
    displayName: 'Download and parse log'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'translation-stage.log'
      artifactName: 'translation-stage-log'
    displayName: 'Publish log artifact'
    condition: succeededOrFailed()
