trigger: none

resources:
  pipelines:
    - pipeline: AROSPipeline16
      source: 'aros-development-team.AROS-pc-i386'
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest

variables:
  SYSTEM_ACCESSTOKEN: $(System.AccessToken)

steps:
- checkout: self
  persistCredentials: true

# Step 1: Download logs, extract warnings, parse submodules, produce reports
- bash: |
    set -euo pipefail

    ORG="aros-development-team"
    PROJECT="AROS"
    PIPELINE_ID=16
    LOG_ID=32

    echo "Fetching latest run ID of pipeline '${ORG}.${PROJECT}-pc-i386'..."
    BUILD_ID=$(curl -sS -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
      "https://dev.azure.com/$ORG/$PROJECT/_apis/pipelines/$PIPELINE_ID/runs?api-version=6.0-preview.1&\$top=1" \
      | jq -r '.value[0].id')

    echo "Pipeline ID: $PIPELINE_ID"
    echo "Latest run ID: $BUILD_ID"

    echo "Downloading specific log ID ($LOG_ID) for build ID $BUILD_ID..."
    curl -sSL -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
      "https://dev.azure.com/$ORG/$PROJECT/_apis/build/builds/$BUILD_ID/logs/$LOG_ID" -o log.txt

    echo "Extracting warning lines..."
    grep -i warning log.txt > warnings.txt || true
    echo "Number of warning lines found: $(wc -l < warnings.txt)"

    echo "Stripping timestamp and absolute path..."
    sed -E 's/^[0-9:.TZ-]+ Z? \/home\/vsts\/work\/[0-9]+\/s\///' warnings.txt > warnings_stripped.txt

    echo "Parsing .gitmodules for submodule paths and URLs..."
    curl -sSL -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
      "https://dev.azure.com/$ORG/$PROJECT/_apis/git/repositories/$PROJECT/items?path=.gitmodules&version=refs/heads/master&includeContent=true" \
      -o .gitmodules

    path=""
    url=""
    declare -A submodules=()
    while IFS= read -r line; do
      if [[ $line =~ ^path\ =\ (.*) ]]; then
        path="${BASH_REMATCH[1]}"
      elif [[ $line =~ ^url\ =\ (.*) ]]; then
        url="${BASH_REMATCH[1]}"
        if [[ -n "$path" && -n "$url" ]]; then
          submodules["$path"]="$url"
          path=""
          url=""
        fi
      fi
    done < .gitmodules

    total_submodules=${#submodules[@]}
    matched_submodules=()

    : > submodule_localization_issues.txt
    : > repository_localization_issues.txt

    for path in "${!submodules[@]}"; do
      count=$(grep -c "^$path/" warnings_stripped.txt || true)
      if [[ $count -gt 0 ]]; then
        matched_submodules+=("$path")
        {
          echo "Submodule: $path (${submodules[$path]})"
          grep "^$path/" warnings_stripped.txt || true
          echo ""
        } >> submodule_localization_issues.txt
      fi
    done

    matched_count=${#matched_submodules[@]}
    echo "Number of submodules with warnings: $matched_count of $total_submodules"

    echo "Collecting unmatched lines..."
    if [[ $matched_count -gt 0 ]]; then
      pattern=$(printf '%s|' "${matched_submodules[@]}")
      pattern="${pattern%|}"
      grep -vE "^($pattern)/" warnings_stripped.txt > repository_localization_issues.txt || true
    else
      cp warnings_stripped.txt repository_localization_issues.txt
    fi

    echo "Wrote matched warnings to submodule_localization_issues.txt"
    echo "Wrote unmatched warnings to repository_localization_issues.txt"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: Download Logs and Analyze Warnings

# Step 2: Download the SSH key file from secure files
- task: DownloadSecureFile@1
  name: GetSSHKey
  inputs:
    secureFile: 'sf-azure-key'

# Step 3: Setup SSH key and config (for SourceForge)
- bash: |
    echo "Setting up SSH key..."
    mkdir -p ~/.ssh
    cp "$(GetSSHKey.secureFilePath)" ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    chmod 700 ~/.ssh

    ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts

    echo "Host web.sourceforge.net" > ~/.ssh/config
    echo "    IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
    echo "    IdentitiesOnly yes" >> ~/.ssh/config
    echo "    StrictHostKeyChecking yes" >> ~/.ssh/config
    echo "    Port 22" >> ~/.ssh/config
    chmod 600 ~/.ssh/config

    echo "SSH key and config setup complete."
  displayName: 'Setup SSH Key and SSH Config for SourceForge'

# Step 4: Upload results via rsync over SSH
- bash: |
    echo "Uploading results via rsync..."
    rsync -avz -e "ssh -F ~/.ssh/config" \
      submodule_localization_issues.txt repository_localization_issues.txt your_sftp_user@web.sourceforge.net:/path/to/destination/
  displayName: 'Upload Results via rsync'
