trigger: none

resources:
  pipelines:
    - pipeline: AROSPipeline16
      source: 'aros-development-team.AROS-pc-i386'
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      echo "Fetching logs for run triggered by pipeline 'aros-development-team.AROS-pc-i386'..."

      run_id=$(echo "$(resources.pipeline.AROSPipeline16.runID)")
      echo "Using run ID: $run_id"

      echo "Downloading logs.zip..."
      curl -sSL -u ":$(System.AccessToken)" \
        "$(System.CollectionUri)$(System.TeamProject)/_apis/build/builds/$run_id/logs.zip?api-version=6.0" \
        -o logs.zip

      echo "Checking logs.zip file type..."
      file logs.zip

      echo "Unzipping logs..."
      unzip -q logs.zip -d logs || (echo "Unzip failed" && file logs.zip && exit 1)
    displayName: 'Download and unzip logs from aros-development-team.AROS-pc-i386'
    env:
      System.AccessToken: $(System.AccessToken)

  - script: |
      echo "Searching logs for known warnings..."

      grep -Er \
        '^- warning: no catalog revision|- warning: ERROR in iconv|- warning: UTF8 conversion|- Warning: missing translation|- Warning: original string|missing in catalog description' logs/ > translation-errors.log || true

      echo "Matched log lines:"
      cat translation-errors.log || echo "No matching warnings found."
    displayName: 'Grep for translation warnings'
