
# Build & Deploy the github-commits.html, archives-uploads.html
# and arosworld-forum.html files for the website.
# To use, you must define the following secret variables
# in the pipeline settings -:
#    SF_RSYNC_USER - sourceforge user to upload as
#    SF_RSYNC_PASSWORD - ...

trigger:
- master

schedules:
- cron: "15 */3 * * *"
  branches:
    include:
    - master
  always: true
  batch: false
  displayName: Hourly trigger

pool:
  vmImage: 'ubuntu-latest'

variables:
    AROSWEBDIR:  '/home/project-web/aros' # Location builds are done in
    AZBUILDPATH: '$(Build.BinariesDirectory)' # workspace path
    AROSDOCSRCDIR: '$(system.defaultWorkingDirectory)' # Path to the source code

steps:
- script: |
    sudo apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893
    sudo apt-get update
    sudo apt-get install -y sshpass
    sudo apt-get install -y python3-feedparser python3-bs4
  displayName: 'Installing AROS build dependencies'

- script: |
    sudo mkdir -p '$(AROSWEBDIR)/htdocs'
    echo '##vso[task.prependpath]$(AROSWEBDIR)/htdocs'
  displayName: 'Setup workspace'

- script: |
    $(AROSDOCSRCDIR)/scripts/web/updatecommits
  displayName: 'Updating commit RSS feed'

- script: |
    $(AROSDOCSRCDIR)/scripts/web/updatearchives
  displayName: 'Updating archives RSS feed'

- script: |
    $(AROSDOCSRCDIR)/scripts/web/updatearosworld
  displayName: 'Updating arosworld RSS feed'

- script: |
    mv $(AROSWEBDIR)/htdocs/commits.html $(AROSWEBDIR)/htdocs/github-commits.html
    mv $(AROSWEBDIR)/htdocs/archives.html $(AROSWEBDIR)/htdocs/archives-uploads.html
    mv $(AROSWEBDIR)/htdocs/arosworld.html $(AROSWEBDIR)/htdocs/arosworld-forum.html
    mkdir -p ~/.ssh
    #ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts
    sshpass -p "$MAPPED_PASS" rsync -avz -e 'ssh -o "StrictHostKeyChecking=no" -p 22' $(AROSWEBDIR)/htdocs/ $MAPPED_USER,aros@web.sourceforge.net:/home/project-web/aros/htdocs/
  env:
    MAPPED_USER: $(SF_RSYNC_USER)
    MAPPED_PASS: $(SF_RSYNC_PASSWORD)
  displayName: 'Deploying website'
