trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  PROJWEBDIR: '/home/project-web' # Location script is run from

steps:
- task: DownloadSecureFile@1
  name: GetSSHKey
  inputs:
    secureFile: 'sf-azure-key'

- script: |
    echo "Setting up SSH key..."
    mkdir -p ~/.ssh
    cp "$(GetSSHKey.secureFilePath)" ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    chmod 700 ~/.ssh

    # Add SourceForge to known hosts (non-interactive SSH)
    ssh-keyscan -t rsa shell.sourceforge.net >> ~/.ssh/known_hosts
  displayName: 'Setup SSH Key for SourceForge'

- script: |
    echo "Checking shell access..."
    if ! ssh -o StrictHostKeyChecking=no "$MAPPED_USER,aros"@shell.sourceforge.net true; then
      echo "Shell not active yet. Creating shell..."
      ssh -t "$MAPPED_USER,aros"@shell.sourceforge.net create

      echo "Waiting for shell to become active (retrying up to 5 times)..."
      for i in $(seq 1 5); do
        if ssh -o StrictHostKeyChecking=no "$MAPPED_USER,aros"@shell.sourceforge.net true; then
          echo "Shell is ready."
          break
        else
          echo "Shell not ready yet, waiting 5 seconds (attempt $i)..."
          sleep 5
        fi
      done
    else
      echo "Shell already active."
    fi

    echo "Running cleanup script on SourceForge..."
    ssh -o StrictHostKeyChecking=yes -p 22 "$MAPPED_USER,aros"@shell.sourceforge.net \
      "cd '$PROJWEBDIR' && ./aros/scripts/unittests-clean"
  env:
    MAPPED_USER: $(SF_RSYNC_USER)
  condition: ne( variables['SF_RSYNC_USER'], '' )
  displayName: 'Run Remote Unittest Cleanup'
