trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PROJWEBDIR:  '/home/project-web' # Location script is run from

steps:
  - script: |
      mkdir -p ~/.ssh
      #ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts
      sshpass -p $MAPPED_PASS ssh -l $MAPPED_USER shell.sourceforge.net "cd $(PROJWEBDIR); ./aros/scripts/nightly2-update"
    env:
      MAPPED_USER: $(SF_RSYNC_USER)
      MAPPED_PASS: $(SF_RSYNC_PASSWORD)
    condition: ne( variables['SF_RSYNC_USER'], '' )
    displayName: 'Updating nightly builds'
