trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PROJWEBDIR:  '/home/project-web' # Location script is run from

steps:
- task: DownloadSecureFile@1
  name: GetSSHKey
  inputs:
    secureFile: 'sf-azure-key'

- script: |
    echo "Setting up SSH key..."
    mkdir -p ~/.ssh
    cp "$(GetSSHKey.secureFilePath)" ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    # Add SourceForge to known hosts (non-interactive SSH)
    ssh-keyscan -t rsa shell.sourceforge.net >> ~/.ssh/known_hosts
  displayName: 'Setup SSH Key for SourceForge'

- script: |
    echo "Running update scripts on SourceForge..."

    ssh -o StrictHostKeyChecking=yes -p 22 "$MAPPED_USER"@shell.sourceforge.net \
      "cd '$PROJWEBDIR' && ./aros/scripts/nightly2-update-frs && ./aros/scripts/nightly2-update"
  env:
    MAPPED_USER: $(SF_RSYNC_USER)  # Set this in your pipeline variable group or UI
  condition: ne( variables['SF_RSYNC_USER'], '' )
  displayName: 'Run Remote Nightly Build Update'
