trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
    PROJWEBDIR:  '/home/project-web' # Location script is run from

steps:
  - script: |
      sudo apt-get install -y sshpass
      mkdir -p ~/.ssh
      #ssh-keyscan -t rsa web.sourceforge.net >> ~/.ssh/known_hosts
      sshpass -p "$MAPPED_PASS" ssh -v -l "$MAPPED_USER" -o "StrictHostKeyChecking=no" -p 22 shell.sourceforge.net create && sshpass -p "$MAPPED_PASS" ssh -v -l "$MAPPED_USER" -o "StrictHostKeyChecking=no" -p 22 shell.sourceforge.net "cd $(PROJWEBDIR) ; ./aros/scripts/nightly2-update ; ./aros/scripts/nightly-update-frs"
    env:
      MAPPED_USER: $(SF_RSYNC_USER)
      MAPPED_PASS: $(SF_RSYNC_PASSWORD)
    condition: ne( variables['SF_RSYNC_USER'], '' )
    displayName: 'Updating nightly builds'
